// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4o41v-K_h7rkBQypo9ShUua8LQek-c80',
    appId: '1:907364014024:web:c73ef8c5c4ba6f68fd52fd',
    messagingSenderId: '907364014024',
    projectId: 'note-d1853',
    authDomain: 'note-d1853.firebaseapp.com',
    storageBucket: 'note-d1853.firebasestorage.app',
    measurementId: 'G-VGFRL1W3ZD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSBd0S8KcidOegYFkwnaXTnW4u62Qr-7Q',
    appId: '1:907364014024:android:26eab63134622b6ffd52fd',
    messagingSenderId: '907364014024',
    projectId: 'note-d1853',
    storageBucket: 'note-d1853.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdPQUVtsZ6RSs8RB5XCfMhF49k818hZBw',
    appId: '1:907364014024:ios:173d580aefee583dfd52fd',
    messagingSenderId: '907364014024',
    projectId: 'note-d1853',
    storageBucket: 'note-d1853.firebasestorage.app',
    iosBundleId: 'com.example.note',
  );
}
